### ISSUE TITLE
Looks like you never published 1.0

### ISSUE THREAD

**Issue by simplenotezy** [cedaro/skip-link-focus#3]
Latest release is still 0.1.0, see: https://github.com/cedaro/skip-link-focus/commit/70a00b1a9d818ac55c8f7f0e5be9015c6d9aff36

**Comment by bradyvercher** [comment]
Hi @simplenotezy, 1.0 is [available on npm](https://www.npmjs.com/package/skip-link-focus), but it does look like I forgot to tag it here.

**Comment by bradyvercher** [comment]
I went ahead and tagged that for posterity. Thanks for bringing it to my attention.
